name: QA UI Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [3.11]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        working-directory: tests/qa-ui-tests-saucedemo
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install allure-pytest allure-commandline

      - name: Run Pytest with Allure
        working-directory: tests/qa-ui-tests-saucedemo
        run: |
          pytest --alluredir=allure-results --maxfail=1 --disable-warnings -q

      - name: Generate Allure Report
        if: always()
        working-directory: tests/qa-ui-tests-saucedemo
        run: |
          allure generate allure-results -o allur
